### ISSUE TITLE
scrape osha data?

### ISSUE THREAD

**Issue by fgregg** [labordata/todo#20]

**Comment by chriszs** [comment]
I contributed to some R code over here that loads it: https://github.com/PublicI/osha-fatality-inspections/blob/5e6dcb580ed141fcef66e8052d223200cf8707c2/osha-fatality-inspections.Rmd#L21-L55

Could make a repo for a SQLite version of this.

**Comment by fgregg** [comment]
i would love that @chriszs !!

**Comment by JeffreyGreenII** [comment]
So I'm not sure what's to do on this, since there's a ton of open source API's for this exact data: https://developer.dol.gov/health-and-safety/dol-osha-enforcement/#osha_accident

Would we like to collect it into a giant db and host it, or somehow merge it into the existing labor db dataset?

**Comment by fgregg** [comment]
doing this https://github.com/labordata/osha-enforcement
